---
name: Deploy to Development

on:
  workflow_call:       # allows calling from merge_to_dev.yml
  workflow_dispatch:   # allows manual triggering

jobs:
  # 🚀 Deploy job
  deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @shopify/cli @shopify/theme

      # Test the token
      - name: Test Shopify connection
        run: shopify theme list --store=${{ secrets.SHOPIFY_FLAG_STORE }}
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}

      # Deploy to development theme
      - name: Deploy to Development Theme
        run: shopify theme push --force --theme="development" --store=${{ secrets.SHOPIFY_FLAG_STORE }}
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
