name: Deploy to Shopify

on:
  push:
    branches:
      - main  # or your theme branch
  workflow_dispatch:  # allows manual triggering

jobs:
  # 🧪 Call test workflow first
  test:
    uses: ./.github/workflows/tests.yml

  # 🚀 Deploy job
  deploy:
    needs: test  # Wait for test job to finish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @shopify/cli
      - run: shopify theme push --force
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
          SHOPIFY_CLI_AUTH_TOKEN: ${{ secrets.SHOPIFY_CLI_AUTH_TOKEN }}
