---
name: Deploy to Production

on:
  push:
    branches:
      - main  # or your theme branch
  workflow_dispatch:  # allows manual triggering

jobs:
  # 🧪 Call test workflow first
  test:
    uses: ./.github/workflows/tests.yml

  # 🚀 Deploy job
  deploy:
    needs: test  # Wait for test job to finish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g @shopify/cli @shopify/theme

      # Test the token
      - name: Test Shopify connection
        run: shopify theme list --store=${{ secrets.SHOPIFY_FLAG_STORE }}
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}

      # Actual deploy
      - run: shopify theme push --force --allow-live --store=${{ secrets.SHOPIFY_FLAG_STORE }} --theme=${{ secrets.SHOPIFY_THEME_ID }}
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
